using System;
using System.Collections.Generic;

namespace SoccerMaster.Tests.Parity
{
    // Data shape of unity/Assets/SoccerMaster/Tests/Fixtures/first_touch_parity.json, generated by
    // tools/nativeFixtures.ts from the web implementation. Public fields only, flat primitives and
    // nested arrays, so both UnityEngine.JsonUtility and System.Text.Json can read it unchanged.

    [Serializable]
    public class GateDto
    {
        public string id;
        public double cx, cy, ax, ay, bx, by;
    }

    [Serializable]
    public class RngDto
    {
        public double seed;
        public List<double> next;
        public List<int> ints;
        public List<double> gaussians;
        public double state;
    }

    [Serializable]
    public class FrameDto
    {
        public int timeMs;
        public string phase;
        public double windowMs;
        public double acc;
        public double rngState;
        public double ballX, ballY, ballVx, ballVy;
        public double playerX, playerY;
        public double defenderX, defenderY;
        public List<string> events;
    }

    [Serializable]
    public class RecordDto
    {
        public int index;
        public double defenderFromX, defenderFromY;
        public string bestGate;
        public string chosenGate;
        public string decision;
        public double accuracy;
        public string execution;
        public string outcome;
    }

    [Serializable]
    public class SummaryDto
    {
        public int reps, strong, acceptable, weak, timeout, clean, ok, loose, through, wide, intercepted;
        public double meanAccuracy;
        public string reads;
        public string touch;
    }

    [Serializable]
    public class RunDto
    {
        public double seed;
        public int reps;
        public bool accessible;
        public string policy;
        public double stepMs;
        public List<FrameDto> frames;
        public List<RecordDto> records;
        public SummaryDto summary;
    }

    [Serializable]
    public class PointDto
    {
        public double x, y;
    }

    [Serializable]
    public class GestureDto
    {
        public List<PointDto> points;
        public bool valid;
        public double directionX, directionY, length, straightness, reach;
        public bool cancel;
        public string gate;
        public double accuracy;
    }

    [Serializable]
    public class TapDto
    {
        public double x, y;
        public string gate;
        public double accuracy;
    }

    [Serializable]
    public class ParityFixture
    {
        public string generator;
        public List<string> source;
        public List<GateDto> gates;
        public List<RngDto> rng;
        public List<RunDto> runs;
        public List<GestureDto> gestures;
        public List<TapDto> taps;
    }
}
