using System.IO;
using NUnit.Framework;
using SoccerMaster.Core.Sim;
using SoccerMaster.Core.Training;
using SoccerMaster.Tests.Parity;
using UnityEngine;

namespace SoccerMaster.Tests.EditMode
{
    /// <summary>
    /// Cross-language parity: the C# drill must reproduce the web implementation's recorded behaviour
    /// (fixture generated by tools/nativeFixtures.ts from src/training/firstTouch.ts).
    /// </summary>
    public class FirstTouchParityTests
    {
        public const string FixturePath = "Assets/SoccerMaster/Tests/Fixtures/first_touch_parity.json";

        private static ParityFixture Load()
        {
            var path = Path.Combine(Path.GetDirectoryName(Application.dataPath) ?? ".", FixturePath);
            Assert.That(File.Exists(path), Is.True, "fixture missing: " + path + " (run `npm run native:fixtures`)");
            var f = JsonUtility.FromJson<ParityFixture>(File.ReadAllText(path));
            Assert.That(f.generator, Is.EqualTo("tools/nativeFixtures.ts"));
            Assert.That(f.runs, Is.Not.Empty);
            return f;
        }

        [Test]
        public void MatchesWebFixtureExactly()
        {
            var result = ParityChecker.Check(Load());
            Assert.That(result.Comparisons, Is.GreaterThan(10_000), "fixture too small to be meaningful");
            Assert.That(result.Failures, Is.Empty, string.Join("\n", result.Failures));
            Debug.Log($"[parity] {result.Comparisons} comparisons, {result.Failures.Count} failures");
        }

        [Test]
        public void FixtureCoversTimeoutAccessibleAndNormalRuns()
        {
            var f = Load();
            Assert.That(f.runs.Exists(r => r.accessible), "no accessible-mode run");
            Assert.That(f.runs.Exists(r => !r.accessible), "no normal run");
            Assert.That(f.runs.Exists(r => r.summary.timeout > 0), "no run exercises the timeout path");
            Assert.That(f.runs.Exists(r => r.summary.through > 0), "no run has a successful touch");
            Assert.That(f.gestures.Exists(g => g.cancel), "no cancel gesture");
            Assert.That(f.taps, Is.Not.Empty);
        }
    }

    public class FirstTouchDrillTests
    {
        [Test]
        public void SameSeedSameStory()
        {
            var a = Run(11, false);
            var b = Run(11, false);
            Assert.That(b.Summarize().Through, Is.EqualTo(a.Summarize().Through));
            Assert.That(b.RngState, Is.EqualTo(a.RngState));
            for (var i = 0; i < a.Records.Count; i++)
            {
                Assert.That(b.Records[i].Decision, Is.EqualTo(a.Records[i].Decision));
                Assert.That(b.Records[i].Outcome, Is.EqualTo(a.Records[i].Outcome));
            }
        }

        [Test]
        public void TimeoutIsSeparateFromExecutionAndOutcome()
        {
            var d = new FirstTouchDrill(3, 1);
            var opened = false;
            for (var t = 0; t < 10_000 && !opened; t += FirstTouchDrill.TickMs)
                opened = d.Step(FirstTouchDrill.TickMs).Exists(e => e.Type == DrillEventType.WindowOpen);
            Assert.That(opened, Is.True, "window never opened");
            Assert.That(d.Phase, Is.EqualTo(Phase.Window));
            Assert.That(d.TimeScale, Is.EqualTo(FirstTouchDrill.DrillSlowScale));
            var openedAt = d.TimeMs;
            // The window is measured in real time; let it lapse without any input.
            Step(d, FirstTouchDrill.WindowMs + FirstTouchDrill.TickMs);
            var rec = d.Records[0];
            Assert.That(rec.Decision, Is.EqualTo(DecisionBand.Timeout));
            Assert.That(rec.Execution, Is.EqualTo(ExecutionBand.Loose));
            Assert.That(rec.ChosenGate.HasValue, Is.True, "timeout still commits a touch, it does not skip the rep");
            Assert.That(d.TimeMs, Is.GreaterThan(openedAt));
        }

        [Test]
        public void AccessibleModeGivesLongerWindow()
        {
            var normal = new FirstTouchDrill(5, 1);
            var accessible = new FirstTouchDrill(5, 1, accessible: true);
            Assert.That(accessible.WindowLimitMs, Is.EqualTo(normal.WindowLimitMs * FirstTouchDrill.AccessibleWindowFactor));
        }

        [Test]
        public void CommitOutsideWindowIsRejected()
        {
            var d = new FirstTouchDrill(9, 1);
            Assert.That(d.Phase, Is.EqualTo(Phase.Serve));
            Assert.That(d.CommitGate(GateId.Forward, 1), Is.Null);
        }

        [Test]
        public void TapAndDrawReadersAgreeOnGateDirection()
        {
            var forward = FirstTouchDrill.ReadTap(new Vec2D(20, 9));
            Assert.That(forward.Gate, Is.EqualTo(GateId.Forward));
            var draw = FirstTouchDrill.ReadDraw(new[]
            {
                FirstTouchDrill.ReceivePoint,
                new Vec2D(12, 9), new Vec2D(14, 9), new Vec2D(16, 9),
            });
            Assert.That(draw.Gate, Is.EqualTo(GateId.Forward));
            Assert.That(draw.Accuracy, Is.GreaterThan(0.9));
        }

        private static FirstTouchDrill Run(int seed, bool accessible)
        {
            var d = new FirstTouchDrill(seed, 4, accessible);
            for (var i = 0; i < 20_000 && d.Phase != Phase.Done; i++)
            {
                var evs = d.Step(FirstTouchDrill.TickMs);
                if (evs.Exists(e => e.Type == DrillEventType.WindowOpen))
                    d.CommitGate(d.Current.BestGate, 0.8);
            }
            Assert.That(d.Phase, Is.EqualTo(Phase.Done));
            return d;
        }

        private static void Step(FirstTouchDrill d, int realMs)
        {
            for (var t = 0; t < realMs; t += FirstTouchDrill.TickMs) d.Step(FirstTouchDrill.TickMs);
        }
    }

    public class IosBuildConfigTests
    {
        [Test]
        public void RequiredScenesAreListed()
        {
            Assert.That(SoccerMaster.Editor.IosBuild.RequiredScenes, Does.Contain(SoccerMaster.Editor.FirstTouchSceneBuilder.ScenePath));
        }

        [Test]
        public void RejectsBadMetadata()
        {
            var id = SoccerMaster.Editor.IosBuild.DefaultBundleId;
            Assert.Throws<UnityEditor.Build.BuildFailedException>(() =>
                SoccerMaster.Editor.IosBuild.Configure("not-a-bundle-id", "0.1.0", 1, "sha"));
            Assert.Throws<UnityEditor.Build.BuildFailedException>(() =>
                SoccerMaster.Editor.IosBuild.Configure(id, "1.0", 1, "sha"));
            Assert.Throws<UnityEditor.Build.BuildFailedException>(() =>
                SoccerMaster.Editor.IosBuild.Configure(id, "0.1.0", 0, "sha"));
        }
    }
}
